KycService:
  Db:
    LogsConnString:
      settings-key: KycService-LogsConnString
      types:
        - AzureTableStorage
    DbConnString:
      settings-key: KycService-DbConnString
  Rabbit:
    Publishers:
      ConnectionString:
        settings-key: UserManagementRabbitMQ
        types:
          - RabbitMq
    Subscribers:
      ConnectionString:
        settings-key: UserManagementRabbitMQ
        types:
          - RabbitMq
SlackNotifications:
    AzureQueue:
        ConnectionString:
            settings-key: SlackNotificationsConnString
            types:
                - AzureTableStorage
        QueueName:
            settings-key: SlackQueueName
MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: MonitoringServiceUrl

